services:
  - type: web
    runtime: docker
    dockerContext: ./server/
    dockerfilePath: ./server/Dockerfile
    name: server
    rootDir: ./server
    domain: datawhiz.server
    envVars:
      - fromGroup: server
    autoDeploy: false

  - type: web
    runtime: docker
    domain: datawhiz.client
    dockerContext: ./client/
    dockerfilePath: ./client/Dockerfile
    name: client
    rootDir: ./client
    envVars:
      - fromGroup: server
    autoDeploy: false
    
