services:
  - type: web
    runtime: docker
    dockerContext: ./server/
    dockerfilePath: ./server/Dockerfile
    name: server
    plan: free
    domain: datawhiz.server
    envVars:
      - fromGroup: server
    autoDeployTrigger: commit

  - type: web
    runtime: docker
    domain: datawhiz.client
    dockerContext: ./client/
    dockerfilePath: ./client/Dockerfile
    name: client
    plan: free
    envVars:
      - fromGroup: server
    autoDeployTrigger: commit
    
